version: '3.8'

services:
  vault:
    build:
      context: ..  # Parent directory as build context
      dockerfile: ./vault/Dockerfile  # Path relative to context
    container_name: vault
    restart: unless-stopped
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    healthcheck:
      test: ["CMD", "bun", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - livintech



networks:
  livintech:
    external: true

